accounts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url, include

from accounts.views import (profile_page, login, register_user, register_company, check_username_email, logout,
                            UpdateProfileView, create_company_name_in_trip, validate_account, user_cockpit,
                            reset_password, thanks_for_registering, user_list_of_inquiries, email_preview)
from travelling.views import corporate_list_of_trips

from seotools.views import render_registration_preamble

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', login, name='user_login'),
    url(r'logout/$', logout, name='user_logout'),
    # url(r'^api/', include('rest_framework.urls', namespace='rest_framework'), name='rest_framework'),
    url(r'^validate/ue/$', check_username_email, name='validate_ue'),
    url(r'^register/$', render_registration_preamble, name='register'),
    url(r'^register/user/$', register_user, name='register_user'),
    url(r'^register/thank-you/$', thanks_for_registering, name='thankyou'),
    url(r'^register/corporate/$', register_company, name='register_company'),
    url(r'^register/corporate/nameonly/$', create_company_name_in_trip, name='create_company_name'),
    url(r'^verify/$', validate_account, name='validate_account'),
    url(r'^console/$', user_cockpit, name='console'),
    url(r'^console/trips/list', corporate_list_of_trips, name='console_trip_list'),
    url(r'^reset/password/$', reset_password, name='reset_password'),
    url(r'email/preview/$', email_preview, name='email_preview'),
    # url(r'^(?P<pk>.+)/inquiries/$', user_list_of_inquiries, name='user_inquiries'),
    url(r'^(?P<pk>.+)/settings/$', UpdateProfileView.as_view(), name='settings'),
    url(r'^(?P<pk>.+)/$', profile_page, name='user_profile'),
]

faq/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url
from faq.views import post_question, post_answer, delete_answer, delete_question, edit_answer, edit_question

app_name = 'faq'
urlpatterns = [
    url(r'post/question/$', post_question, name='post_question'),
    url(r'post/answer/$', post_answer, name='post_answer'),
    url(r'edit/question/(?P<instance>.)+/$', edit_question, name='edit_question'),
    url(r'edit/answer/(?P<instance>.)+/$', edit_answer, name='edit_answer'),
    url(r'delete/question/(?P<instance>.)+/$', delete_question, name='delete_question'),
    url(r'delete/answer/(?P<instance>.)+/$', delete_answer, name='delete_answer'),
]

inquiries/urls.py
from django.conf.urls import re_path

from inquiries.views import create_inquiry, list_inquiries, mark_as_read, handle_inquiry_state


app_name = 'inquiries'
urlpatterns = [
    re_path(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/inquire/', create_inquiry, name='inquire_trip'),
    re_path(r'^inquiries/update/status/$', mark_as_read, name='update_inquiry'),
    re_path(r'^inquiries/change/([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/$', handle_inquiry_state,
            name='change_lead_status'),
    re_path(r'^inquiries/([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/$', list_inquiries, name='inquiry_list'),
    re_path(r'^inquiries/$', list_inquiries, name='inquiry_list'),
]

jagdreisencheck/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

import os

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render_to_response
from django.views.static import serve

from travelling.views import TripSitemap
from accounts.views import CorporateSitemap

# Must be left here as the JET Dashboard would crash otherwise.
from jet.dashboard.dashboard_modules import google_analytics_views, send_mail_views


admin.autodiscover()
urlpatterns = [
    re_path(r'^sitemap\.xml', sitemap, {'sitemaps': {
        'cmspages': CMSSitemap,
        'trips': TripSitemap,
        'companies': CorporateSitemap
    }}),
    re_path(r'^robots\.txt', include('robots.urls')),
]

urlpatterns += i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    re_path(r'^jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    re_path(r'^admin/django-ses/', include('django_ses.urls')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts'), name='accounts'),
    re_path(r'^accounts/', include('django.contrib.auth.urls'), name='auth'),
    re_path(r'^jagdreisen/', include('travelling.urls', namespace='travelling'), name='travelling'),
    re_path(r'^jagdreisen/', include('pricing.urls', namespace='pricing'), name='pricing'),
    re_path(r'^portal/', include('inquiries.urls'), name='inquires'),
    re_path(r'^jagdreisen/', include('search.urls', namespace='search'), name='search'),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^slideshow/', include('slideshow.urls', namespace='slideshow'), name='slideshow'),
    re_path(r'^mailing/', include('mailing.urls', namespace='mailing'), name='mailing'),
    re_path(r'^news/', include('newsletter.urls'), name='newsletter'),
    re_path(r'^faq/', include('faq.urls'), name='faq'),
    re_path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    re_path(r'^flat/', include('django.contrib.flatpages.urls')),
    re_path(r'^akademie/', include('podcasting.urls')),
    re_path(r'^akademie/', include('djangocms_blog.urls', namespace='Blog')),
    # re_path(r'^seo/', include('seotools.urls', namespace='seotools')),
    # re_path(r'^djangocms_comments/', include('djangocms_comments.urls')),
    re_path(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
      re_path('^media/(?P<path>.*)$', serve,
          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns
    
    
def handler400(request, *args, **argv):
    return render_to_response(template_name='errorhandlers/400-Bad-Request.html', context={}, status=400)


def handler401(request, *args, **argv):
    return render_to_response(template_name='errorhandlers/401-Unauthorized.html', context={}, status=401)


def handler403(request, *args, **argv):
    return render_to_response(template_name='errorhandlers/403-Forbidden.html', context={}, status=403)


def handler404(request, *args, **argv):
    return render_to_response(template_name='errorhandlers/404-Not-Found.html', context={}, status=404)


def handler500(request, *args, **argv):
    return render_to_response(template_name='errorhandlers/500-Internal-Error.html', context={}, status=500)

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

travelling/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url

from travelling.views import (create_a_trip, retrieve_trip_details, create_game_instance, rate_trip, modify_trip,
                              return_options_for_rating, align_headline_image, reply_to_rating,
                              update_trip_rating, request_trip_deletion, revise_trip_deletion, delete_a_trip,
                              approve_trip, rate_review)


app_name = 'travelling'
urlpatterns = [

    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/update/rating/$', update_trip_rating, name='update_rating'),

    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/rate/$', rate_trip, name='rate_trip'),
    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/request/delete/$', request_trip_deletion,
        name='request_trip_deletion'),
    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/revise/delete/$', revise_trip_deletion,
        name='revise_trip_deletion'),
    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/admin/delete/$', delete_a_trip, name='delete_trip'),
    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/admin/approve/$', approve_trip, name='approve_trip'),
    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/modify/$', modify_trip, name='modify_trip'),

    url(r'^([a-zA-Z0-9\-\_]+)/([\w]{2})/([a-z0-9_\-]+)/$', retrieve_trip_details, name='show_trip'),

    url(r'^rating-choices/$', return_options_for_rating, name='rating_options'),

    url(r'^create/trip/$', create_a_trip, name='create_trip'),
    url(r'^create/game/$', create_game_instance, name='create_game_instance'),

    url(r'^update/trip/headline-image/$', align_headline_image, name='change_headline_y_position'),
    url(r'^reply/rating/$', reply_to_rating, name='reply_to_rating'),
    url(r'^rate_review/$', rate_review, name='rate_review'),
]

inquiries/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField
from djmoney.models.fields import MoneyField

from accounts.models import User, CorporateProfile, generate_short_uuid4
from jagdreisencheck.lists import *
from travelling.models import Trip, Game


# Create your models here.
class TripInquiry(models.Model):
    
    iq = models.CharField(verbose_name=_('Inquiry ID'), max_length=30, null=True, blank=False, unique=True)

    trip = models.ForeignKey(verbose_name=_('Associated Trip'), blank=False, null=True, to=Trip,
                             on_delete=models.SET_NULL)
    user = models.ForeignKey(verbose_name=_('Inquiring User'), blank=False, null=False, to=User,
                             on_delete=models.CASCADE)

    name = models.CharField(verbose_name=_("Name"), max_length=150, null=True, blank=True)
    email = models.EmailField(verbose_name=_("E-Mail"), null=True, blank=True)
    phone = models.CharField(verbose_name=_('Phone'), null=True, blank=True, max_length=35)

    # num_of_hunters = models.IntegerField(verbose_name=_("Number of Hunters"), null=True, blank=True)
    num_of_non_hunters = models.IntegerField(verbose_name=_("Number of accompanying Persons"), null=True, blank=True)

    hunting_type = models.CharField(verbose_name=_('Primary Hunting Type'), choices=HUNTING_TYPE_LIST, default='P',
                                    max_length=1)
    accommodation = models.CharField(verbose_name=_('Accommodation'), choices=ACCOMODATION_LIST, max_length=2,
                                     null=True)

    time_start = models.DateField(verbose_name=_('When would you like to start the trip?'), blank=False, null=True,
                                  error_messages={'invalid': _('Please provide a valid date. Format: dd.mm.yyyy')})
    time_end = models.DateField(verbose_name=_('When would you like to end the trip?'), blank=False, null=True,
                                error_messages={'invalid': _('Please provide a valid date. Format: dd.mm.yyyy')})

    inquiry = RichTextField(verbose_name=_("Further Details, Wishes & Questions"), null=True, blank=False)
    consent_to_be_contacted = models.BooleanField(verbose_name=_("Consent to be contacted"), default=False, blank=False)

    date = models.DateTimeField(verbose_name=_("Date of Inquiry"), auto_now_add=True)
    traveller_status = models.CharField(verbose_name=_('Travel Status'), choices=TRAVELLER_CHOICE_LIST, default='OP',
                                        max_length=2)
    read = models.BooleanField(verbose_name=_('Inquiry has been opened'), default=False, blank=False, choices=YNList)
    
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        
        if not self.iq:
            self.iq = generate_short_uuid4()
            
        return super(TripInquiry, self).save(force_insert, force_insert, using, update_fields)

    def __str__(self):
        string = ""
        try:
            string = "{}".format(self.trip.name)
        except TypeError or AttributeError or ValueError:
            pass
        
        try:
            string = "{} {}".format(string, self.user.user.email)
        except AttributeError or ValueError:
            pass

        return string


class HunterData(models.Model):
    inquiry = models.ForeignKey(verbose_name=_('Associated Inquiry'), to=TripInquiry,
                                on_delete=models.CASCADE)

    game = models.ManyToManyField(verbose_name=_('Primary Game to hunt'), to=Game, blank=False)
    budget = MoneyField(verbose_name=_('Budget'), blank=False, null=True, default_currency='EUR', decimal_places=2,
                        max_digits=8)
    license_since = models.IntegerField(verbose_name=_('Year the hunting license was obtained'), blank=False, null=True,
                                        choices=YEAR_LIST())
    shooting_experience = models.IntegerField(verbose_name=_('Max. Shooting distance'), blank=False, null=True)
    physical_fitness = models.IntegerField(verbose_name=_('Physical Fitness'), choices=FITNESS_LIST, null=True,
                                           blank=False)
    age = models.IntegerField(verbose_name=_('Age'), null=True, blank=True)
    
    name = models.CharField(verbose_name=_('Name'), max_length=75, null=True, blank=True)

    def __str__(self):
        return u'%s' % self.inquiry.user.get_full_name

inquiries/forms.py
from django.forms import models, forms, SelectMultiple, TextInput, Select, DateInput
from django.utils.translation import ugettext_lazy as _
from recaptcha3.fields import ReCaptchaField

from travelling.models import Trip
from inquiries.models import TripInquiry, HunterData
from jagdreisencheck.custom_fields import JRCMoneyWidget


class CustomDateInput(DateInput):
    input_type = 'date'


class TripInquiryForm(models.ModelForm):
    recaptcha = ReCaptchaField()
    
    class Meta:
        model = TripInquiry
        fields = ['phone', 'num_of_non_hunters', 'hunting_type', 'accommodation', 'time_start',
                  'time_end', 'inquiry', 'consent_to_be_contacted', 'recaptcha', 'name', 'email']
        widgets = {
            'time_start': CustomDateInput(),
            'time_end': CustomDateInput(),
        }
        
        
class HunterDataForm(models.ModelForm):

    class Meta:
        model = HunterData
        fields = ['game', 'budget', 'license_since', 'shooting_experience', 'physical_fitness', 'age', 'name']
        widgets = {
            'budget': JRCMoneyWidget(attrs={'label': _('Budget')}),
            'game': SelectMultiple(attrs={'hide_add_btns': True, 'multiple': True}),
            'name': TextInput(attrs={'no_label': True})
        }
        
        
class HunterDataFormset(models.BaseInlineFormSet):
    
    def clean(self):
        return super(HunterDataFormset, self).clean()
    
    
class ChangeInquiryStatusForm(models.ModelForm):
    
    class Meta:
        model = Trip
        fields = ['lead_status']
        widgets = {
            'lead_status': Select(attrs={'no_label': True, 'is_submit': True})
        }

inquiries/templates/inquiries/company/change-inquiry-state.html
{% load sekizai_tags %}

<form class="form" method="post" action="{% url 'inquiries:change_lead_status' trip.company.slug trip.country.code|slugify trip.region|slugify %}">
  {% csrf_token %}
  {% include 'base/components/fields.html' with field=form.lead_status disable_empty=True %}
</form>

{% addtoblock 'js' %}
  <script>
    $('form select').on('change', function(){
      $(this).closest('form').submit();
    });
  </script>
{% endaddtoblock %}

inquiries/templates/inquiries/company/inquiry-list.html
{% extends 'base/structure/base.html' %}
{% load i18n staticfiles sekizai_tags %}

{% block title %}
  {% trans 'Your Trip Inquiries' %}
{% endblock %}

{% block headline-img-source %}
  {% static 'assets/../../../../jagdreisencheck/static/images/background/Hilly_Landscape.jpg' %}
{% endblock %}

{% block headline-content-containerized %}
  <div class="row">
    <div class="col-12">
      <h1>{% trans 'Your Trip Inquiries' %}</h1>
    </div>
  </div>
{% endblock %}


{% block content %}

  {% regroup inquiries by read as inquiry_list %}

  <div class="container nav-padding">
    <h1>{% trans 'Your Trip Inquiries' %}</h1>
    <hr/>

    <p>
      <i class="fa fa-exclamation-circle"></i>
      {% blocktrans %}
        Here you can view all your inquiries. The inquiries will be sorted based on their status. If you open an inquiry it will be marked as read.
        Please note that the status is also visible to the inquiring hunter so he may follow up.
        If you experience any issues please contact us via e-mail:
      {% endblocktrans %}
      <a href="mailto:brieftaube@jagdreisencheck.de" style="text-decoration: underline;">brieftaube@jagdreisencheck.de</a>.
    </p>

    {% for status in inquiry_list %}
      <h2>{% if status.grouper == True %}{% trans 'Read inquiries' context 'inquiries' %}{% else %}{% trans 'Unread inquiries' context 'inquiries' %}{% endif %}</h2>

      <div id="accordion-{{ forloop.counter }}" class="accordion mb-3">
        {% for inquiry in status.list %}
          <div class="card mb-3">
            <div class="card-header" id="headingOne">
              <h3>
                <button class="btn btn-link btn-inquiry" data-toggle="collapse" data-target="#{{ status.grouper }}-{{ forloop.counter }}" aria-expanded="false" data-read="{{ inquiry.read }}" data-url="{% url 'inquiries:update_inquiry' %}" data-id="{{ inquiry.iq }}" style="white-space: normal">
                  <i class="fa fa-chevron-right"></i>
                  {% blocktrans with region=inquiry.trip.region country=inquiry.trip.country.name company=inquiry.trip.company.name %}
                    Your inquiry for a trip to {{ region }}, {{ country }} offered by {{ company }}.
                  {% endblocktrans %}
                </button>
                <small style="float: right; font-size: 0.9rem; margin: 5px 0;">
                  {% trans 'Date' %}: {{ inquiry.date|date }}<br/>
                  {% trans 'ID' %}: {{ inquiry.iq }}<br>
                  {% trans 'Status' %}: {% if inquiry.read %}{% trans 'Read' %}{% else %}{% trans 'Unread' %}{% endif %}
                </small></h3>
            </div>

            <div id="{{ status.grouper }}-{{ forloop.counter }}" class="collapse" data-parent="#accordion">
              <div class="card-body">
                <h4>
                  <i class="fa fa-sort"></i>
                  {% trans 'Key facts' %}
                </h4>

                <div class="row">

                  <div class="col-xs-12 col-lg-6">
                    <div class="table-responsive">
                      <table class="table table-hover">
                        <tr>
                          <td>{% trans 'Trip' %}</td>
                          <td>
                            <a href="{% url 'travelling:show_trip' inquiry.trip.company.slug inquiry.trip.country.code|slugify inquiry.trip.region|slugify %}">
                              {{ inquiry.trip.region }}, {{ inquiry.trip.country.name }}
                            </a>
                          </td>
                        </tr>
                        <tr>
                          <td>{% trans 'Main contact' %}</td>
                          <td>
                            <a href="{% url 'accounts:user_profile' inquiry.trip.company.slug %}">
                              {{ inquiry.user.get_full_name }}
                            </a>
                          </td>
                        </tr>
                        <tr>
                          <td>{% trans 'Travel dates' %}</td>
                          <td>
                            {{ inquiry.time_start }} - {{ inquiry.time_end }}
                          </td>
                        </tr>
                        <tr>
                          <td>{% trans 'Contact info' %}</td>
                          <td>
                            <phone>{{ inquiry.phone }}</phone><br/>
                            <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                          </td>
                        </tr>

                      </table>
                    </div>
                  </div>

                  <div class="col-xs-12 col-lg-6">
                    <div class="table-responsive">

                      <table class="table table-hover">
                        <tr>
                          <td>{% trans 'Accommodation' %}</td>
                          <td>
                            {{ inquiry.get_accommodation_display }}
                          </td>
                        </tr>
                        <tr>
                          <td>{% trans 'Hunting type' %}</td>
                          <td>
                            {{ inquiry.get_hunting_type_display }}
                          </td>
                        </tr>
                        <tr>
                          <td>{% trans 'Number of persons' %}</td>
                          <td>
                            Hunters: {{ inquiry.hunterdata_set.all|length }},<br/>
                            Companions: {{ inquiry.num_of_non_hunters }}
                          </td>
                        </tr>
                      </table>

                    </div>
                  </div>
                </div>

                <h4>
                  <i class="fa fa-comments"></i>
                  {% trans 'Inquiry details' %}
                </h4>
                <hr/>
                <p>{% trans 'The hunters inquiry' %}: {{ inquiry.inquiry }}</p>
                <br/>

                <h4>
                  <i class="fa fa-user"></i>
                  {% trans 'Hunters' %}
                </h4>
                <hr/>

                <div class="row">
                  {% for hunter in inquiry.hunterdata_set.all %}
                    <div class="col-xs-12 col-lg-6">
                      <h5>{% trans 'Hunter' %} {{ forloop.counter }}:
                        {% if forloop.first %}{{ inquiry.user.get_full_name }}{% else %}{{ hunter.name }}{% endif %}
                      </h5>
                      <table class="table table-hover">
                        <tr>
                          <td>{% trans 'Desired game' %}</td>
                          <td>{{ hunter.game.all|join:", " }}</td>
                        </tr>
                        <tr>
                          <td>{% trans 'License' %}</td>
                          <td>{{ hunter.license_since }}</td>
                        </tr>
                        <tr>
                          <td>{% trans 'Max. shot distance' %}</td>
                          <td>{{ hunter.shooting_experience }} {% trans 'm' context 'meter' %}</td>
                        </tr>
                        <tr>
                          <td>{% trans 'Physical fitness' %}</td>
                          <td>{{ hunter.get_physical_fitness_display }}</td>
                        </tr>
                        <tr>
                          <td>{% trans 'Age' %}</td>
                          <td>{{ hunter.age }}</td>
                        </tr>
                        <tr>
                          <td>{% trans 'Budget' %}</td>
                          <td>{{ hunter.budget }}</td>
                        </tr>

                      </table>
                    </div>
                  {% endfor %}
                </div>

                <h4>
                  <i class="fa fa-cogs"></i>
                  {% trans 'Actions' %}
                </h4>
                <hr/>

                <a href="mailto:{{ inquiry.user.email }}?subject={% blocktrans with region=inquiry.trip.region country=inquiry.trip.country.name date=inquiry.date|date %}Your inquiry for our trip offer to {{ region }}, {{ country }} from {{ date }} on Jagdreisencheck{% endblocktrans %}" class="btn btn-darkblue">
                  <i class="fa fa-envelope"></i>
                  {% trans 'Contact the hunter' %}
                </a>
                &nbsp;
                <a href="mailto:brieftaube@jagdreisencheck.de?subject={% blocktrans with iq=inquiry.iq %}Issue with the inquiry ID: {{ iq }}{% endblocktrans %}" class="btn btn-outline-darkblue">
                  <i class="fa fa-exclamation-triangle"></i>
                  {% trans 'Report an issue' %}
                </a>

              </div>
            </div>
          </div>
        {% endfor %}
      </div>

    {% endfor %}

  </div>

  {% addtoblock 'css' %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/new-styles/inquire-trip-page.css' %}"/>
  {% endaddtoblock %}

  {% addtoblock 'js' %}
    <script src="{% static 'scripts/components/inquiry-scripts.min.js' %}"></script>
  {% endaddtoblock %}

{% endblock %}